/*
 * The goal of this program is to let user guess a number randomly generated by the program.
 */

import java.util.Random;
import java.util.Scanner;

// Class name must be same with the file name.
// All Java source code must be inside a class
// Pay attention to indentation, semicolon (";"),
// parenthesis ("(", ")") and braces ("{", "}")
public class GuessMyNumber {
    // Main method is the starting point of any Java program
    public static void main(String[] args) {
        // Generate a random number between 1 and 10
        Random random = new Random();
        int numberToGuess = random.nextInt(10) + 1;

        // Prompt the user for a guess
        System.out.println("I'm thinking of a number between 1 and 10 (including both). Can you guess what it is?");
        System.out.print("Type a number: ");

        // Read the user's guess
        Scanner scanner = new Scanner(System.in);
        int userGuess = scanner.nextInt();

        // Display the user's guess
        System.out.println("Your guess is: " + userGuess);

        // Reveal the correct number
        System.out.println("The number I was thinking of is: " + numberToGuess);

        // Calculate the difference
        int difference = Math.abs(numberToGuess - userGuess);

        // Display how far off the user was
        System.out.println("You were off by: " + difference);

        scanner.close();
    }
}